# Step 1: Build the JAR
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Step 2: Run the JAR
FROM openjdk:17.0.1-jdk-slim
WORKDIR /app
COPY --from=build /app/target/email-writer-0.0.1-SNAPSHOT.jar app.jar

# Use Render's PORT environment variable
ENV PORT=9090
EXPOSE 9090

ENTRYPOINT ["java","-jar","app.jar"]
